name: New Invoice Extension
description: File a new e-Invoice extension request
title: "[Extension]: "
labels: ["extension", "new"]
projects: ["svanteschubert/EN16931-Extension-Components"]
assignees:
  - edmundgray
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new e-Invoice extension request, please search in the existing issues for a similar request! 
        
        ---
        
        Thank you for taking the time to file an e-Invoice extension request. To address this request as fast as possible, we need some information.
  - type: dropdown
    id: InvoiceCore
    attributes:
      label: Relative EU Invoice
      description: "This extension is referring to the following EU Invoice Core:"      
      options:
        - uncertain
        - urn:cen.eu:en16931:2017
        - urn:cen.eu:en16931:2025 (unreleased)
      default: 1
    validations:
      required: true
  - type: input
    id: BusinessName
    attributes:
      label: Business Name
      description: "Which is the name, expressing its semantic briefly and adequate?"
      placeholder: "The Business name for this extension component"
    validations:
      required: true
  - type: textarea
    id: BusinessRequirement
    attributes:
      label: Business Requirement
      description: Why is the data set required?
    validations:
      required: true
  - type: checkboxes
    id: Usage
    attributes:
      label: Usage
      description: "This feature is used in the following relations:"
      options:
      - label: uncertain
      - label: B2G
      - label: B2B
      - label: B2C
  - type: checkboxes
    id: Sectors
    attributes:
      label: Required by Sectors
      description: "This feature is used by the following industry sectors:"
      options:
      - label: uncertain
      - label: (*)  all sectors
      - label: Automotive industry
      - label: Building materials industry
      - label: Book trade
      - label: Chemical industry
      - label: Electrical industry / electrical wholesale
      - label: Electronics, software and telecommunications industry
      - label: Gas transmission and distribution
      - label: Consumer goods industry
      - label: Furniture industry
      - label: Paper manufacturers / wholesalers / processing industry
      - label: Tyre and wheel manufacturers
      - label: Sanitary industry
      - label: Forwarding industry
      - label: Electricity and gas
      - label: Telecommunications
      - label: Textile industry
      - label: Transport industry
      - label: Insurance industry
        required: false
  - type: checkboxes
    id: MemberStates
    attributes:
      label: Required by EU Member States
      description: "This feature is used in the following states of the European Union (EU) or European Free Trade Association (EFTA):"
      options:
      - label: uncertain
      - label: (*)  all across Europe
      - label: (AT) Austria
      - label: (BE) Belgium
      - label: (BG) Bulgaria
      - label: (HR) Croatia
      - label: (CY) Cyprus
      - label: (CZ) Czechia
      - label: (DK) Denmark
      - label: (EE) Estonia
      - label: (FI) Finland
      - label: (FR) France
      - label: (DE) Germany
      - label: (EL) Greece
      - label: (HU) Hungary
      - label: (IS) Iceland
      - label: (IE) Ireland
      - label: (IT) Italy
      - label: (LV) Latvia
      - label: (LI) Liechtenstein
      - label: (LT) Lithuania
      - label: (LU) Luxembourg
      - label: (MT) Malta
      - label: (NL) Netherlands
      - label: (NO) Norway
      - label: (PL) Poland
      - label: (PT) Portugal
      - label: (RO) Romania
      - label: (SK) Slovakia
      - label: (SI) Slovenia
      - label: (ES) Spain
      - label: (SE) Sweden
      - label: (CH) Switzerland
        required: false
  - type: dropdown
    id: VAT_Reporting
    attributes:
      label: VAT_Reporting
      description: Is this information required by VAT_Reporting?
      options:
        - "uncertain"
        - "yes"
        - "no"
      default: 0
    validations:
      required: true
  - type: textarea
    id: LegalReference
    attributes:
      label: Legal Reference
      description: "If there is a legal requirement, please provide an URL to each law. (in case of no direct link, in following lines the position and/or the wording!)"
      placeholder: "https://someLegalReference.com/theLaw"
    validations:
      required: false
  - type: dropdown
    id: occurences
    attributes:
      label: Occurences
      description: "Please provide the required cardinality, expressing possible future occurences:"
      options:
        - "uncertain"
        - "0..1"
        - "1..1"
        - "0..n"
        - "1..n"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: dataType
    attributes:
      label: Data Group
      description: "Is the required semantic a data group or single data?"
      options:
        - "uncertain"
        - "BT (Business Term  - single   data)"
        - "BG (Business Group - multiple data)"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: parent
    attributes:
      label: Parent
      multiple: true
      description: "Are you aware of its semantic context in EN16931? \n(in case of BG its parent and for BT its group)"
      options:
        - "uncertain"
        - "TopLevel"
        - "BG-1	(INVOICE NOTE)"
        - "BG-2	(PROCESS CONTROL)"
        - "BG-3	(PRECEDING INVOICE REFERENCE)"
        - "BG-4	(SELLER)"
        - "BG-5	(SELLER POSTAL ADDRESS)"
        - "BG-6	(SELLER CONTACT)"
        - "BG-7	(BUYER)"
        - "BG-8	(BUYER POSTAL ADDRESS)"
        - "BG-9	(BUYER CONTACT)"
        - "BG-10	(PAYEE)"
        - "BG-11	(SELLER TAX REPRESENTATIVE PARTY)"
        - "BG-12	(SELLER TAX REPRESENTATIVE POSTAL ADDRESS)"
        - "BG-13	(DELIVERY INFORMATION)"
        - "BG-14	(DELIVERY OR INVOICE PERIOD)"
        - "BG-15	(DELIVER TO ADDRESS)"
        - "BG-16	(PAYMENT INSTRUCTIONS)"
        - "BG-17	(CREDIT TRANSFER)"
        - "BG-18	(PAYMENT CARD INFORMATION)"
        - "BG-19	(DIRECT DEBIT)"
        - "BG-20	(DOCUMENT LEVEL ALLOWANCES)"
        - "BG-21	(DOCUMENT LEVEL CHARGES)"
        - "BG-22	(DOCUMENT TOTALS)"
        - "BG-23	(VAT BREAKDOWN)"
        - "BG-24	(ADDITIONAL SUPPORTING DOCUMENTS)"
        - "BG-25	(INVOICE LINE)"
        - "BG-26	(INVOICE LINE PERIOD)"
        - "BG-27	(INVOICE LINE ALLOWANCES)"
        - "BG-28	(INVOICE LINE CHARGES)"
        - "BG-29	(PRICE DETAILS)"
        - "BG-30	(LINE VAT INFORMATION)"
        - "BG-31	(ITEM INFORMATION)"
        - "BG-32	(ITEM ATTRIBUTES)"
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: ChangedRules
    attributes:
      label: Business Rules being changed
      description: "If business rules need adoption please mention them:"
      options:
      - label: uncertain 
      - label: BR-1	An Invoice shall have a Specification identifier (BT-24).
      - label: BR-2	An Invoice shall have an Invoice number (BT-1).
      - label: BR-3	An Invoice shall have an Invoice issue date (BT-2).
      - label: BR-4	An Invoice shall have an Invoice type code (BT-3).
      - label: BR-5	An Invoice shall have an Invoice currency code (BT-5).
      - label: BR-6	An Invoice shall contain the Seller name (BT-27).
      - label: BR-7	An Invoice shall contain the Buyer name (BT-44).
      - label: BR-8	An Invoice shall contain the Seller postal address (BG-5).
      - label: BR-9	The Seller postal address (BG-5) shall contain a Seller country code (BT-40).
      - label: BR-10	An Invoice shall contain the Buyer postal address (BG-8).
      - label: BR-11	The Buyer postal address shall contain a Buyer country code (BT-55).
      - label: BR-12	An Invoice shall have the Sum of Invoice line net amount (BT-106).
      - label: BR-13	An Invoice shall have the Invoice total amount without VAT (BT-109).
      - label: BR-14	An Invoice shall have the Invoice total amount with VAT (BT-112).
      - label: BR-15	An Invoice shall have the Amount due for payment (BT-115).
      - label: BR-16	An Invoice shall have at least one Invoice line (BG-25).
      - label: BR-17	The Payee name (BT-59) shall be provided in the Invoice, if the Payee (BG-10) is different from the Seller (BG-4).
      - label: BR-18	The Seller tax representative name (BT-62) shall be provided in the Invoice, if the Seller (BG-4) has a Seller tax representative party (BG-11).
      - label: BR-19	The Seller tax representative postal address (BG-12) shall be provided in the Invoice, if the Seller (BG-4) has a Seller tax representative party (BG-11).
      - label: BR-20	The Seller tax representative postal address (BG-12) shall contain a Tax representative country code (BT-69), if the Seller (BG-4) has a Seller tax representative party (BG-11).
      - label: BR-21	Each Invoice line (BG-25) shall have an Invoice line identifier (BT-126).
      - label: BR-22	Each Invoice line (BG-25) shall have an Invoiced quantity (BT-129).
      - label: BR-23	An Invoice line (BG-25) shall have an Invoiced quantity unit of measure code (BT-130).
      - label: BR-24	Each Invoice line (BG-25) shall have an Invoice line net amount (BT-131).
      - label: BR-25	Each Invoice line (BG-25) shall contain the Item name (BT-153).
      - label: BR-26	Each Invoice line (BG-25) shall contain the Item net price (BT-146).
      - label: BR-27	The Item net price (BT-146) shall NOT be negative.
      - label: BR-28	The Item gross price (BT-148) shall NOT be negative.
      - label: BR-29	If both Invoicing period start date (BT-73) and Invoicing period end date (BT-74) are given then the Invoicing period end date (BT-74) shall be later or equal to the Invoicing period start date (BT-73).
      - label: BR-30	If both Invoice line period start date (BT-134) and Invoice line period end date (BT-135) are given then the Invoice line period end date (BT-135) shall be later or equal to the Invoice line period start date (BT-134).
      - label: BR-31	Each Document level allowance (BG-20) shall have a Document level allowance amount (BT-92).
      - label: BR-32	Each Document level allowance (BG-20) shall have a Document level allowance VAT category code (BT-95).
      - label: BR-33	Each Document level allowance (BG-20) shall have a Document level allowance reason (BT-97) or a Document level allowance reason code (BT-98).
      - label: BR-36	Each Document level charge (BG-21) shall have a Document level charge amount (BT-99).
      - label: BR-37	Each Document level charge (BG-21) shall have a Document level charge VAT category code (BT-102).
      - label: BR-38	Each Document level charge (BG-21) shall have a Document level charge reason (BT-104) or a Document level charge reason code (BT-105).
      - label: BR-41	Each Invoice line allowance (BG-27) shall have an Invoice line allowance amount (BT-136).
      - label: BR-42	Each Invoice line allowance (BG-27) shall have an Invoice line allowance reason (BT-139) or an Invoice line allowance reason code (BT-140).
      - label: BR-43	Each Invoice line charge (BG-28) shall have an Invoice line charge amount (BT-141).
      - label: BR-44	Each Invoice line charge (BG-28) shall have an Invoice line charge reason (BT-144) or an Invoice line charge reason code (BT-145).
      - label: BR-45	Each VAT breakdown (BG-23) shall have a VAT category taxable amount (BT-116).
      - label: BR-46	Each VAT breakdown (BG-23) shall have a VAT category tax amount (BT-117).
      - label: BR-47	Each VAT breakdown (BG-23) shall be defined through a VAT category code (BT-118).
      - label: BR-48	Each VAT breakdown (BG-23) shall have a VAT category rate (BT-119), except if the Invoice is not subject to VAT.
      - label: BR-49	A Payment instruction (BG-16) shall specify the Payment means type code (BT-81).
      - label: BR-50	A Payment account identifier (BT-84) shall be present if Credit transfer (BG-16) information is provided in the Invoice.
      - label: BR-51	The last 4 to 6 digits of the Payment card primary account number (BT-87) shall be present if Payment card information (BG-18) is provided in the Invoice.
      - label: BR-52	Each Additional supporting document (BG-24) shall contain a Supporting document reference (BT-122).
      - label: BR-53	If the VAT accounting currency code (BT-6) is present, then the Invoice total VAT amount in accounting currency (BT-111) shall be provided.
      - label: BR-54	Each Item attribute (BG-32) shall contain an Item attribute name (BT-160) and an Item attribute value (BT-161).
      - label: BR-55	Each Preceding Invoice reference (BG-3) shall contain a Preceding Invoice reference (BT-25).
      - label: BR-56	Each Seller tax representative party (BG-11) shall have a Seller tax representative VAT identifier (BT-63).
      - label: BR-57	Each Deliver to address (BG-15) shall contain a Deliver to country code (BT-80).
      - label: BR-61	If the Payment means type code (BT-81) means SEPA credit transfer, Local credit transfer or Non-SEPA international credit transfer, the Payment account identifier (BT-84) shall be present.
      - label: BR-62	The Seller electronic address (BT-34) shall have a Scheme identifier.
      - label: BR-63	The Buyer electronic address (BT-49) shall have a Scheme identifier.
      - label: BR-64	The Item standard identifier (BT-157) shall have a Scheme identifier
      - label: BR-65	The Item classification identifier (BT-158) shall have a Scheme identifier
      - label: BR-CO-3	Value added tax point date (BT-7) and Value added tax point date code (BT-8) are mutually exclusive.
      - label: BR-CO-4	Each Invoice line (BG-25) shall be categorized with an Invoiced item VAT category code (BT-151).
      - label: BR-CO-5	Document level allowance reason code (BT-98) and Document level allowance reason (BT-97) shall indicate the same type of allowance.
      - label: BR-CO-6	Document level charge reason code (BT-105) and Document level charge reason (BT-104) shall indicate the same type of charge.
      - label: BR-CO-7	Invoice line allowance reason code (BT-140) and Invoice line allowance reason (BT-139) shall indicate the same type of allowance reason.
      - label: BR-CO-8	Invoice line charge reason code (BT-145) and Invoice line charge reason (BT144) shall indicate the same type of charge reason.
      - label: BR-CO-9	The Seller VAT identifier (BT-31), the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48) shall have a prefix in accordance with ISO code ISO 3166 1 alpha-2 by which the country of issue may be identified. Nevertheless, Greece may use the prefix ‘EL’.
      - label: BR-CO-10	Sum of Invoice line net amount (BT-106) = ? Invoice line net amount (BT-131).
      - label: BR-CO-11	Sum of allowances on document level (BT-107) = ? Document level allowance amount (BT-92).
      - label: BR-CO-12	Sum of charges on document level (BT-108) = ? Document level charge amount (BT-99).
      - label: BR-CO-13	Invoice total amount without VAT (BT-109) = ? Invoice line net amount (BT-131) - Sum of allowances on document level (BT-107) + Sum of charges on document level (BT-108).
      - label: BR-CO-14	Invoice total VAT amount (BT-110) = ? VAT category tax amount (BT-117).
      - label: BR-CO-15	Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).
      - label: BR-CO-16	Amount due for payment (BT-115) = Invoice total amount with VAT (BT-112) -Paid amount (BT-113 + Rounding amount (BT-114).
      - label: BR-CO-17	VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals.
      - label: BR-CO-18	An Invoice shall at least have one VAT breakdown group (BG-23).
      - label: BR-CO-19	If Invoicing period (BG-14) is used, the Invoicing period start date (BT-73) or the Invoicing period end date (BT-74) shall be filled, or both.
      - label: BR-CO-20	If Invoice line period (BG-26) is used, the Invoice line period start date (BT-134) or the Invoice line period end date (BT-135) shall be filled, or both.
      - label: BR-CO-21	Each Document level allowance (BG-20) shall contain a Document level allowance reason (BT-97) or a Document level allowance reason code (BT-98), or both.
      - label: BR-CO-22	Each Document level charge (BG-21) shall contain a Document level charge reason (BT-104) or a Document level charge reason code (BT-105), or both.
      - label: BR-CO-23	Each Invoice line allowance (BG-27) shall contain an Invoice line allowance reason (BT-139) or an Invoice line allowance reason code (BT-140), or both.
      - label: BR-CO-24	Each Invoice line charge (BG-28) shall contain an Invoice line charge reason (BT-144) or an Invoice line charge reason code (BT-145), or both.
      - label: BR-CO-25	In case the Amount due for payment (BT-115) is positive, either the Payment due date (BT-9) or the Payment terms (BT-20) shall be present.
      - label: BR-CO-26	In order for the buyer to automatically identify a supplier, the Seller identifier (BT-29), the Seller legal registration identifier (BT-30) and/or the Seller VAT identifier (BT-31) shall be present.
